# Generated by Django 5.1.2 on 2024-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_userprofiles_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='instagram',
            field=models.URLField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='strava',
            field=models.URLField(default=None, max_length=100, null=True),
        ),
    ]
