# Generated by Django 5.1.2 on 2024-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_userprofiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile-photos/'),
        ),
    ]
