# Generated by Django 5.1.2 on 2024-10-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_userprofiles_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile-photos/'),
        ),
    ]
