# Generated by Django 5.1.2 on 2024-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_userprofiles_bike_bikephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikephoto',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='bike_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
