# Generated by Django 5.1.2 on 2024-10-30 10:40

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_remove_userprofiles_bike_userprofiles_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
