# Generated by Django 5.1.2 on 2024-11-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_userprofiles_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikephoto',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='bikephoto',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
