# Generated by Django 5.1.2 on 2024-11-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_alter_bikephoto_options_bikephoto_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bikephoto',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
